### ISSUE TITLE
lab6, part 1 Q 1

### ISSUE THREAD

**Issue by kidistbetter105** [DS4PS/cpp-523-sum-2021#14]
Lab 6
part 1
Q1
Am getting this Error every time when I run the code. 
Can I get help on this. 

 Error in eval(predvars, data, env) : object 'y' not found

Thanks !

**Comment by lecy** [comment]
Please include code with your questions - it is really hard to guess at what is going wrong without seeing what you are doing. 

----

# Simple Rules for Clear Questions

## (2) Include Your Code

This question is difficult to answer because we don’t know how the error was generated unless you share your code:

> I am trying to merge my data but I keep getting the error message, “x is not a factor”.

You need to show the code that generated the error message. Try something like:

> I am trying to merge my data, but I keep getting the error message, “cannot merge object type list”. Here is my code:

```r
x <- data.frame( id=letters[1:10], v1=rnorm(10) )
y <- data.frame( id=letters[1:10], v2=rbinom(10) )
z <- list( x, y )
merge( y, z )
```

**Comment by kidistbetter105** [comment]
HI!
Sorry about that. But now I figured and submitted my assignment. 
Thanks!
